### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rakshakannu**
#### Delete everything from this line onwards ####
 #### Please create one PR per idea, and make the changes in README.md, not this file! ####
 Idea template should look like: 
 * Global Trend: A global trend currently
 * Action: An action or a verb
 * Idea: An idea that you can generate with these.
 * Any suggestions/ solution to an Idea!
 ---
 
  #### For example, an idea could be : ####
  * Global trend: 3D Printing
  * Action: The need to eat
  * Idea: Developing 3D printed edible food!

### CODE REVIEW

**Review by radhikasethi2011 — COMMENTED** [review]
would you like to add an Idea with it too?

**Comment by rakshakannu** [comment]
How do I add an idea? create another column in the table?

**Comment by radhikasethi2011** [comment]
> How do I add an idea? create another coloum in the table?

No, under the **Ideas** section

**Comment by rakshakannu** [comment]
Oh okay, yeah would love to!

**Comment by radhikasethi2011** [comment]
Great work!

**Pull request merged**
